import type { PortfolioEntry } from "@/types/types";

export const PortfolioEntryList: PortfolioEntry[] = [
  {
    title: "NGS Bulk RNAseq Workflow",
    type: ["Project"],
    description:
      "Nextflow pipeline for processing of raw bulk RNAseq files with Docker containerization",
    skills: ["Nextflow", "Docker", "AWS"],
  },
  {
    title: "manan-chopra.com",
    type: ["Project"],
    description:
      "Portfolio website to display my projects, publications, and experience.",
    skills: ["React", "Typescript"],
  },
  {
    title:
      "Human Retinal Ganglion Cell Neurons Generated by Synchronous BMP inhibition and Transcription Factor Mediated Reprogramming",
    type: ["Publication"],
    date: new Date(2023, 6),
    description:
      "Study outlining protocol for direct differentiation of retinal ganglion cells from human stem cells, and thorough bioinformatics analysis and validation of the generated cells.",
    skills: [
      "Python",
      "R",
      "Jupyter Notebook",
      "Scientific Writing",
      "Snakemake",
    ],
  },
];
