import type { PortfolioEntry } from "@/types/types";

export const PortfolioEntryList: PortfolioEntry[] = [
  {
    title: "NGS Bulk RNAseq Workflow",
    type: ["Project"],
    description:
      "Nextflow pipeline for processing of raw bulk RNAseq files with Docker containerization",
    skills: ["Nextflow", "Docker", "AWS"],
    repoLink: "https://github.com/recursivelymanan/NGS-bulk-pipeline",
  },
  {
    title: "manan-chopra.com",
    type: ["Project"],
    description:
      "Portfolio website to display my projects, publications, and experience.",
    skills: ["React", "Typescript"],
    repoLink: "https://github.com/recursivelymanan/manan-chopra.com",
  },
  {
    title:
      "Human Retinal Ganglion Cell Neurons Generated by Synchronous BMP inhibition and Transcription Factor Mediated Reprogramming",
    type: ["Publication"],
    date: new Date(2023, 6),
    description:
      "Study outlining protocol for direct differentiation of retinal ganglion cells from human stem cells, and thorough bioinformatics analysis and validation of the generated cells.",
    skills: [
      "Python",
      "R",
      "Jupyter Notebook",
      "Scientific Writing",
      "Snakemake",
    ],
    repoLink: "https://github.com/WahlinLab/Human_RGC-iN",
    prodLink: "https://www.nature.com/articles/s41536-023-00327-x",
  },
  {
    title: "Genedex",
    type: ["Project"],
    description: "Mobile app for quick gene lookup.",
    skills: ["React-Native", "Typescript"],
    repoLink: "https://github.com/recursivelymanan/Genedex",
    prodLink: "apple.co/3Z4EcHV",
  },
];
